/**
 * @author Levi Armstrong <levi.armstrong@gmail.com>
 *
 * @copyright Copyright (C) 2022 Levi Armstrong <levi.armstrong@gmail.com>
 *
 * @par License
 * GNU Lesser General Public License Version 3, 29 June 2007
 * @par
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 * @par
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * @par
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
#ifndef TESSERACT_GUI_COMMON_EVENT_TYPE_H
#define TESSERACT_GUI_COMMON_EVENT_TYPE_H

#include <QEvent>
namespace tesseract_gui::events
{
// clang-format off
enum class EventType : int
{
  EVENT_TYPE = QEvent::Type::User + 1000,

  // Application Events
  APP_TYPES_START                  = EVENT_TYPE,
  APP_STATUS_MESSAGE_SHOW          = APP_TYPES_START + 1,
  APP_STATUS_MESSAGE_CLEAR         = APP_TYPES_START + 2,
  APP_TYPES_END                    = APP_TYPES_START + 3,

  // Render Events
  RENDER_TYPES_START                  = APP_TYPES_END,
  PRE_RENDER                          = RENDER_TYPES_START + 1,
  RENDER                              = RENDER_TYPES_START + 2,
  SNAP_INTERVALS                      = RENDER_TYPES_START + 3,
  SPAWN_FROM_DESCRIPTION              = RENDER_TYPES_START + 4,
  SPAWN_FROM_PATH                     = RENDER_TYPES_START + 5,
  HOVER_TO_SCENE                      = RENDER_TYPES_START + 6,
  LEFT_CLICK_TO_SCENE                 = RENDER_TYPES_START + 7,
  RIGHT_CLICK_TO_SCENE                = RENDER_TYPES_START + 8,
  DROPDOWN_MENU_ENABLED               = RENDER_TYPES_START + 9,
  KEY_RELEASE_ON_SCENE                = RENDER_TYPES_START + 10,
  KEY_PRESS_ON_SCENE                  = RENDER_TYPES_START + 11,
  LEFT_CLICK_ON_SCENE                 = RENDER_TYPES_START + 12,
  RIGHT_CLICK_ON_SCENE                = RENDER_TYPES_START + 13,
  BLOCK_ORBIT                         = RENDER_TYPES_START + 14,
  HOVER_ON_SCENE                      = RENDER_TYPES_START + 15,
  SPAWN_CLONE_FROM_NAME               = RENDER_TYPES_START + 16,
  DROP_ON_SCENE                       = RENDER_TYPES_START + 17,
  SCROLL_ON_SCENE                     = RENDER_TYPES_START + 18,
  DRAG_ON_SCENE                       = RENDER_TYPES_START + 19,
  MOUSE_PRESS_ON_SCENE                = RENDER_TYPES_START + 20,
  RENDER_TYPES_END                    = RENDER_TYPES_START + 21,

  // Tool Path
  TOOL_PATH_ADD             = RENDER_TYPES_END + 1,
  TOOL_PATH_REMOVE          = RENDER_TYPES_END + 2,
  TOOL_PATH_REMOVE_ALL      = RENDER_TYPES_END + 3,
  TOOL_PATH_REMOVE_SELECTED = RENDER_TYPES_END + 4,
  TOOL_PATH_HIDE            = RENDER_TYPES_END + 5,
  TOOL_PATH_HIDE_ALL        = RENDER_TYPES_END + 6,
  TOOL_PATH_SHOW            = RENDER_TYPES_END + 7,
  TOOL_PATH_SHOW_ALL        = RENDER_TYPES_END + 8,
  TOOL_PATH_OPEN            = RENDER_TYPES_END + 9,
  TOOL_PATH_SAVE            = RENDER_TYPES_END + 10,
  TOOL_PATH_TYPES_END       = RENDER_TYPES_END + 11,

  // Scene Graph
  SCENE_GRAPH_TYPES_START                = TOOL_PATH_TYPES_END,
  SCENE_GRAPH_CLEAR                      = SCENE_GRAPH_TYPES_START + 1,
  SCENE_GRAPH_SET                        = SCENE_GRAPH_TYPES_START + 2,
  SCENE_GRAPH_ADD_LINK                   = SCENE_GRAPH_TYPES_START + 3,
  SCENE_GRAPH_ADD_JOINT                  = SCENE_GRAPH_TYPES_START + 4,
  SCENE_GRAPH_MOVE_LINK                  = SCENE_GRAPH_TYPES_START + 5,
  SCENE_GRAPH_MOVE_JOINT                 = SCENE_GRAPH_TYPES_START + 6,
  SCENE_GRAPH_REMOVE_LINK                = SCENE_GRAPH_TYPES_START + 7,
  SCENE_GRAPH_REMOVE_JOINT               = SCENE_GRAPH_TYPES_START + 8,
  SCENE_GRAPH_REPLACE_JOINT              = SCENE_GRAPH_TYPES_START + 9,
  SCENE_GRAPH_MODIFY_LINK_VISIBILITY     = SCENE_GRAPH_TYPES_START + 10,
  SCENE_GRAPH_MODIFY_LINK_VISIBILITY_ALL = SCENE_GRAPH_TYPES_START + 11,
  SCENE_GRAPH_STATE_CHANGED              = SCENE_GRAPH_TYPES_START + 12,
  SCENE_GRAPH_PLOT                       = SCENE_GRAPH_TYPES_START + 13,
  SCENE_GRAPH_TYPES_END                  = SCENE_GRAPH_TYPES_START + 14,

  // Contact Results
  CONTACT_RESULTS_TYPES_START         = SCENE_GRAPH_TYPES_END,
  CONTACT_RESULTS_CLEAR               = CONTACT_RESULTS_TYPES_START + 1,
  CONTACT_RESULTS_SET                 = CONTACT_RESULTS_TYPES_START + 2,
  CONTACT_RESULTS_REMOVE              = CONTACT_RESULTS_TYPES_START + 3,
  CONTACT_RESULTS_VISIBILITY          = CONTACT_RESULTS_TYPES_START + 4,
  CONTACT_RESULTS_VISIBILITY_ALL      = CONTACT_RESULTS_TYPES_START + 5,
  CONTACT_RESULTS_COMPUTE             = CONTACT_RESULTS_TYPES_START + 6,
  CONTACT_RESULTS_TYPES_END           = CONTACT_RESULTS_TYPES_START + 7,

  // Contact Results
  ACM_TYPES_START     = CONTACT_RESULTS_TYPES_END,
  ACM_CLEAR           = ACM_TYPES_START + 1,
  ACM_SET             = ACM_TYPES_START + 2,
  ACM_ADD             = ACM_TYPES_START + 3,
  ACM_REMOVE          = ACM_TYPES_START + 4,
  ACM_REMOVE_LINK     = ACM_TYPES_START + 5,
  ACM_VISIBILITY      = ACM_TYPES_START + 6,
  ACM_GENERATE        = ACM_TYPES_START + 7,
  ACM_TYPES_END       = ACM_TYPES_START + 8,

  // Command Language
  COMMAND_LANGUGE_TYPES_START     = ACM_TYPES_END,
  CL_COMPOSITE_INSTRUCTION_CLEAR  = COMMAND_LANGUGE_TYPES_START + 1,
  CL_COMPOSITE_INSTRUCTION_SET    = COMMAND_LANGUGE_TYPES_START + 2,
  CL_COMPOSITE_INSTRUCTION_REMOVE = COMMAND_LANGUGE_TYPES_START + 3,
  COMMAND_LANGUGE_TYPES_END       = COMMAND_LANGUGE_TYPES_START + 4,

  // Group Joint States
  GROUP_JOINT_STATES_TYPES_START  = COMMAND_LANGUGE_TYPES_END,
  GROUP_JOINT_STATES_CLEAR        = GROUP_JOINT_STATES_TYPES_START + 1,
  GROUP_JOINT_STATES_SET          = GROUP_JOINT_STATES_TYPES_START + 2,
  GROUP_JOINT_STATES_ADD          = GROUP_JOINT_STATES_TYPES_START + 3,
  GROUP_JOINT_STATES_REMOVE       = GROUP_JOINT_STATES_TYPES_START + 4,
  GROUP_JOINT_STATES_REMOVE_GROUP = GROUP_JOINT_STATES_TYPES_START + 5,
  GROUP_JOINT_STATES_SHOW         = GROUP_JOINT_STATES_TYPES_START + 6,
  GROUP_JOINT_STATES_HIDE         = GROUP_JOINT_STATES_TYPES_START + 7,
  GROUP_JOINT_STATES_TYPES_END    = GROUP_JOINT_STATES_TYPES_START + 8,

  // Group TCPS
  GROUP_TCPS_TYPES_START  = GROUP_JOINT_STATES_TYPES_END,
  GROUP_TCPS_CLEAR        = GROUP_TCPS_TYPES_START + 1,
  GROUP_TCPS_SET          = GROUP_TCPS_TYPES_START + 2,
  GROUP_TCPS_ADD          = GROUP_TCPS_TYPES_START + 3,
  GROUP_TCPS_REMOVE       = GROUP_TCPS_TYPES_START + 4,
  GROUP_TCPS_REMOVE_GROUP = GROUP_TCPS_TYPES_START + 5,
  GROUP_TCPS_TYPES_END    = GROUP_TCPS_TYPES_START + 6,

  // Kinematic Groups
  KINEMATIC_GROUPS_TYPES_START  = GROUP_TCPS_TYPES_END,
  KINEMATIC_GROUPS_CLEAR        = KINEMATIC_GROUPS_TYPES_START + 1,
  KINEMATIC_GROUPS_SET          = KINEMATIC_GROUPS_TYPES_START + 2,
  KINEMATIC_GROUPS_ADD_CHAIN    = KINEMATIC_GROUPS_TYPES_START + 3,
  KINEMATIC_GROUPS_ADD_JOINT    = KINEMATIC_GROUPS_TYPES_START + 4,
  KINEMATIC_GROUPS_ADD_LINK     = KINEMATIC_GROUPS_TYPES_START + 5,
  KINEMATIC_GROUPS_REMOVE       = KINEMATIC_GROUPS_TYPES_START + 6,
  KINEMATIC_GROUPS_TYPES_END    = KINEMATIC_GROUPS_TYPES_START + 7,

  // Environment Commands
  ENVIRONMENT_COMMANDS_TYPES_START  = KINEMATIC_GROUPS_TYPES_END,
  ENVIRONMENT_COMMANDS_CLEAR        = ENVIRONMENT_COMMANDS_TYPES_START + 1,
  ENVIRONMENT_COMMANDS_SET          = ENVIRONMENT_COMMANDS_TYPES_START + 2,
  ENVIRONMENT_COMMANDS_APPEND       = ENVIRONMENT_COMMANDS_TYPES_START + 3,
  ENVIRONMENT_COMMANDS_TYPES_END    = ENVIRONMENT_COMMANDS_TYPES_START + 4,

  // Environment Commands
  ENVIRONMENT_TYPES_START     = ENVIRONMENT_COMMANDS_TYPES_END,
  ENVIRONMENT_APPLY_COMMANDS  = ENVIRONMENT_TYPES_START + 1,
  ENVIRONMENT_SET_STATE       = ENVIRONMENT_TYPES_START + 2,
  ENVIRONMENT_TYPES_END       = ENVIRONMENT_TYPES_START + 3,

  // Joint Trajectory
  JOINT_TRAJECTORY_TYPES_START     = ENVIRONMENT_TYPES_END,
  JOINT_TRAJECTORY_ADD             = JOINT_TRAJECTORY_TYPES_START + 1,
  JOINT_TRAJECTORY_REMOVE          = JOINT_TRAJECTORY_TYPES_START + 2,
  JOINT_TRAJECTORY_REMOVE_ALL      = JOINT_TRAJECTORY_TYPES_START + 3,
  JOINT_TRAJECTORY_REMOVE_SELECTED = JOINT_TRAJECTORY_TYPES_START + 4,
  JOINT_TRAJECTORY_OPEN            = JOINT_TRAJECTORY_TYPES_START + 5,
  JOINT_TRAJECTORY_SAVE            = JOINT_TRAJECTORY_TYPES_START + 6,
  JOINT_TRAJECTORY_PLOT            = JOINT_TRAJECTORY_TYPES_START + 7,
  JOINT_TRAJECTORY_TOOLBAR_STATE   = JOINT_TRAJECTORY_TYPES_START + 8,
  JOINT_TRAJECTORY_TYPES_END       = JOINT_TRAJECTORY_TYPES_START + 9,

  // Manipulation
  MANIPULATION_TYPES_START = JOINT_TRAJECTORY_TYPES_END,
  MANIPULATION_CHANGED     = MANIPULATION_TYPES_START + 1,
  MANIPULATION_TYPES_END   = MANIPULATION_TYPES_START + 2,
};
}

#endif // TESSERACT_GUI_COMMON_EVENT_TYPE_H
