name: Clang-Format

on:
  push:
    branches:
      - main
  pull_request:

  # allow manually starting this workflow
  workflow_dispatch:

jobs:
  clang_format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Run clang format
        run: |
          sudo apt update
          sudo apt install -y git clang-format-8
          ./.run-clang-format
          output=$(git diff)
          if [ -n "$output" ]; then exit 1; else exit 0; fi
